### ISSUE TITLE
⚠ Regexp loop

### ISSUE THREAD

**Issue by SDSWanderer** [shaunburdick/jira2slack#1]
Hello! It's not this lib issue, but I think we need to leave it open and place it here for people like me, who will spend few nights debugging their code...

Here is regexp from sources:
```javascript
// Citations
.replace(/\?\?((?:.[^?]|[^?].)+)\?\?/g, '_-- $1_')
```

In some reason in V8-based environments (Chrome, node.js) it can hangs your app!
Try this:
```javascript
// if you have powerful CPU - 100 may be not enough, so place greeter number here
// 'w' - can be any letter
const testString = '??'+'w'.repeat(100) 
testString.replace(/\?\?((?:.[^?]|[^?].)+)\?\?/g, '_-- $1_')
```

In Chrome it will hang your tab, in Node.js - block thread or kill process with internal error.
In Safari works ok, so looks like it's V8 issue.

**Comment by shaunburdick** [comment]
Hmmm. I wonder if there is a way for me to optimize that regex a little. I'll play around with it and see what I can come up with. (Also RIP that tab I tried that in)

**Comment by shaunburdick** [comment]
I did a lazy simplification of the regex that seems to work a lot better. Pushed 1.0.1 to npm if you want to give it a shot. Sorry about the nights of debugging :-/

**Comment by SDSWanderer** [comment]
Looks like this fix helps, I can't see any issues for about 3 days. Thanks!
