### ISSUE TITLE
Gitlab Smart Links Markdown Conversion Issue

### ISSUE THREAD

**Issue by corbetmw** [shaunburdick/jira2slack#17]
When using Gitlab links in Jira comments, the link is broken when the Jira Cloud Slack app creates a Slack message for it. Please see the other reports listed below:

1. https://jira.atlassian.com/browse/JRACLOUD-76111
2. https://community.atlassian.com/t5/Jira-Software-questions/Jira-Cloud-bot-messages-are-rewriting-the-content-and-breaking/qaq-p/2028835

The root cause is this regex replace in [index.js](https://github.com/shaunburdick/jira2slack/blob/481be88c4c51e7c2547336b53af7f3f70b341ac2/index.js#L61). At this replace, it's parsing the Smart Link formatting of the link, which replaces the dashes as tildes. Please see [this example](https://regex101.com/r/S8jSYE/1
) for more detail.

**Comment by corbetmw** [comment]
Resolved in most recent PR.

**Comment by shaunburdick** [comment]
Thank you for your contributions @corbetmw I have pushed a new version with your fixes in it!
